SELECT * FROM AIRCRAFT
SELECT * FROM FDPLIMIT
SELECT * FROM FLIGHT
SELECT * FROM PARING


CREATE VIEW FDPLIMIT_UNION AS 
SELECT F.AT_TM_INITIAL_TIME, F.AT_TM_FINAL_TIME, AT_SECTORS_1 AS AT_SECTORS_N_FLIGHTS, 
												 AT_TM_SECTORS_1 AS AT_TM_SECTORS
FROM FDPLIMIT F
UNION
SELECT F.AT_TM_INITIAL_TIME, F.AT_TM_FINAL_TIME, AT_SECTORS_2, AT_TM_SECTORS_2
FROM FDPLIMIT F
UNION
SELECT F.AT_TM_INITIAL_TIME, F.AT_TM_FINAL_TIME, AT_SECTORS_3, AT_TM_SECTORS_3
FROM FDPLIMIT F
UNION
SELECT F.AT_TM_INITIAL_TIME, F.AT_TM_FINAL_TIME, AT_SECTORS_4, AT_TM_SECTORS_4
FROM FDPLIMIT F
UNION
SELECT F.AT_TM_INITIAL_TIME, F.AT_TM_FINAL_TIME, AT_SECTORS_5, AT_TM_SECTORS_5
FROM FDPLIMIT F
UNION
SELECT F.AT_TM_INITIAL_TIME, F.AT_TM_FINAL_TIME, AT_SECTORS_6, AT_TM_SECTORS_6
FROM FDPLIMIT F
UNION
SELECT F.AT_TM_INITIAL_TIME, F.AT_TM_FINAL_TIME, AT_SECTORS_7, AT_TM_SECTORS_7
FROM FDPLIMIT F
UNION
SELECT F.AT_TM_INITIAL_TIME, F.AT_TM_FINAL_TIME, AT_SECTORS_8, AT_TM_SECTORS_8
FROM FDPLIMIT F
UNION
SELECT F.AT_TM_INITIAL_TIME, F.AT_TM_FINAL_TIME, AT_SECTORS_9, AT_TM_SECTORS_9
FROM FDPLIMIT F
UNION
SELECT F.AT_TM_INITIAL_TIME, F.AT_TM_FINAL_TIME, AT_SECTORS_10, AT_TM_SECTORS_10
FROM FDPLIMIT F
--ORDER BY 3


SELECT *
FROM FDPLIMIT_UNION


SELECT FORMAT(CAST(F.AT_TM_INITIAL_TIME AS TIME),'hh\:mm') AS INITIAL_HOUR, 
	   FORMAT(CAST(F.AT_TM_FINAL_TIME AS TIME),'hh\:mm') AS FINAL_HOUR, 
	   FORMAT(CAST(F.AT_TM_SECTORS AS TIME),'hh\:mm') AS MAX_HOUR,
	   F.AT_SECTORS_N_FLIGHTS
	   
FROM FDPLIMIT_UNION F
ORDER BY  3 ASC --3 DESC ,4 DESC